[WIP] Unit Tests for Movement Module
henrytran28/i-love-tetris pull request #20
Opened 2018-11-13 17:22 UTC by ctlai95

2018-11-24 00:30 UTC, henrytran28 requested changes
Partial review for now. Will review again once the other PR gets in.

2018-11-24 00:30 UTC, henrytran28 commented on src/movement/movement.lua
> +        if square.y + 1 >= self.board.height or self.board.boardTetrominosMatrix[square.x][square.y + 1] ~= 0 then
LOL I can't believe we missed this. Also could you change this and the other movements to not isFilled too 😸

2018-11-24 00:30 UTC, henrytran28 commented on src/movement/movement_test.lua
> +function getTetrominoWidth(tetromino)
Can you change these 2 functions to local

2018-11-24 00:30 UTC, henrytran28 commented on src/movement/movement_test.lua
> +    it("getTetrominoWidth", function()
GetTetrominoWidth to be consistent right? Same with other functions

2018-11-24 00:30 UTC, henrytran28 commented on src/movement/movement_test.lua
> +            -- initialize some variables
don't need this comment lol

2018-11-26 18:59 UTC, ctlai95 commented on src/movement/movement.lua
> +        if square.y + 1 >= self.board.height or self.board.boardTetrominosMatrix[square.x][square.y + 1] ~= 0 then
actually I caught this one in the python version of this PR, it just never got merged so I didn't fix it here lol
But yea good catch on the !isFilled

2018-11-27 00:36 UTC, ctlai95 commented on src/movement/movement_test.lua
> +    it("getTetrominoWidth", function()
I was gonna incorporate widths/heights at different rotation states but I didn't end up using it I think.

2018-11-28 03:01 UTC, henrytran28 commented on src/movement/movement_test.lua
> +    it("getTetrominoWidth", function()
so is this never used?

2018-11-28 03:02 UTC, henrytran28 commented on src/movement/movement_test.lua
> +    it("getTetrominoWidth", function()
oh so should these be removed?

2018-11-29 06:30 UTC, ctlai95 commented on src/movement/movement_test.lua
> +    it("getTetrominoWidth", function()
eh i think its fine to leave them

2019-01-15 07:48 UTC, ctlai95 commented
@henrytran28 ready for review :)

2019-01-21 00:27 UTC, henrytran28 approved these changes

2019-01-21 00:28 UTC, merged